version: 0.0
os: linux
files:
  - source: docker/load_image.sh
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 10
      runas: ec2-user
