
name: test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build-app:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Run a one liner
              run: |
                echo "hello world"

    build-api:
        runs-on: windows-latest
        steps:
            - run: echo "building API"

    build-db:
        needs: build-app
        runs-on: windows-latest
        steps:
            - run: echo "hello win"

    package:
        needs: [build-app, build-db]
        runs-on: ubuntu-latest
        steps:
            - run: echo "echlo"

            